UINT.mapinfo1lev =
{
    '// MAPINFO for Doom 2 - Intermission Wrapper Mod for OBLIGE generated 32-Map Megawads\n'
    '\n'
    'defaultmap\n'
    '{\n'
    '	sucktime = 5\n'
    '}\n'
    '\n'
    'map MAP01 lookup "HUSTR_1"\n'
    '{\n'
    '	titlepatch = "CWILV00"\n'
    '	next = "EndTitle"\n'
    '	secretnext = "EndTitle"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 7\n'
    '	par = 300\n'
    '	music = "$MUSIC_RUNNIN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP02 lookup "HUSTR_2"\n'
    '{\n'
    '	titlepatch = "CWILV01"\n'
    '	next = "MAP03"\n'
    '	secretnext = "MAP03"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_STALKS"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP03 lookup "HUSTR_3"\n'
    '{\n'
    '	titlepatch = "CWILV02"\n'
    '	next = "MAP04"\n'
    '	secretnext = "MAP04"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_COUNTD"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP04 lookup "HUSTR_4"\n'
    '{\n'
    '	titlepatch = "CWILV03"\n'
    '	next = "MAP05"\n'
    '	secretnext = "MAP05"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_BETWEE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP05 lookup "HUSTR_5"\n'
    '{\n'
    '	titlepatch = "CWILV04"\n'
    '	next = "MAP06"\n'
    '	secretnext = "MAP06"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DOOM"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP06 lookup "HUSTR_6"\n'
    '{\n'
    '	titlepatch = "CWILV05"\n'
    '	next = "MAP07"\n'
    '	secretnext = "MAP07"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_THE_DA"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP07 lookup "HUSTR_7"\n'
    '{\n'
    '	titlepatch = "CWILV06"\n'
    '	next = "MAP08"\n'
    '	secretnext = "MAP08"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	map07special\n'
    '	music = "$MUSIC_SHAWN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP08 lookup "HUSTR_8"\n'
    '{\n'
    '	titlepatch = "CWILV07"\n'
    '	next = "MAP09"\n'
    '	secretnext = "MAP09"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBLU"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP09 lookup "HUSTR_9"\n'
    '{\n'
    '	titlepatch = "CWILV08"\n'
    '	next = "MAP10"\n'
    '	secretnext = "MAP10"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_IN_CIT"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP10 lookup "HUSTR_10"\n'
    '{\n'
    '	titlepatch = "CWILV09"\n'
    '	next = "MAP11"\n'
    '	secretnext = "MAP11"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DEAD"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP11 lookup "HUSTR_11"\n'
    '{\n'
    '	titlepatch = "CWILV10"\n'
    '	next = "MAP12"\n'
    '	secretnext = "MAP12"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_STLKS2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP12 lookup "HUSTR_12"\n'
    '{\n'
    '	titlepatch = "CWILV11"\n'
    '	next = "MAP13"\n'
    '	secretnext = "MAP13"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_THEDA2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP13 lookup "HUSTR_13"\n'
    '{\n'
    '	titlepatch = "CWILV12"\n'
    '	next = "MAP14"\n'
    '	secretnext = "MAP14"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DOOM2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP14 lookup "HUSTR_14"\n'
    '{\n'
    '	titlepatch = "CWILV13"\n'
    '	next = "MAP15"\n'
    '	secretnext = "MAP15"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBL2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP15 lookup "HUSTR_15"\n'
    '{\n'
    '	titlepatch = "CWILV14"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP31"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_RUNNI2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP16 lookup "HUSTR_16"\n'
    '{\n'
    '	titlepatch = "CWILV15"\n'
    '	next = "MAP17"\n'
    '	secretnext = "MAP17"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_DEAD2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP17 lookup "HUSTR_17"\n'
    '{\n'
    '	titlepatch = "CWILV16"\n'
    '	next = "MAP18"\n'
    '	secretnext = "MAP18"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_STLKS3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP18 lookup "HUSTR_18"\n'
    '{\n'
    '	titlepatch = "CWILV17"\n'
    '	next = "MAP19"\n'
    '	secretnext = "MAP19"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ROMERO"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP19 lookup "HUSTR_19"\n'
    '{\n'
    '	titlepatch = "CWILV18"\n'
    '	next = "MAP20"\n'
    '	secretnext = "MAP20"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_SHAWN2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP20 lookup "HUSTR_20"\n'
    '{\n'
    '	titlepatch = "CWILV19"\n'
    '	next = "MAP21"\n'
    '	secretnext = "MAP21"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_MESSAG"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP21 lookup "HUSTR_21"\n'
    '{\n'
    '	titlepatch = "CWILV20"\n'
    '	next = "MAP22"\n'
    '	secretnext = "MAP22"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_COUNT2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP22 lookup "HUSTR_22"\n'
    '{\n'
    '	titlepatch = "CWILV21"\n'
    '	next = "MAP23"\n'
    '	secretnext = "MAP23"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBL3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP23 lookup "HUSTR_23"\n'
    '{\n'
    '	titlepatch = "CWILV22"\n'
    '	next = "MAP24"\n'
    '	secretnext = "MAP24"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_AMPIE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP24 lookup "HUSTR_24"\n'
    '{\n'
    '	titlepatch = "CWILV23"\n'
    '	next = "MAP25"\n'
    '	secretnext = "MAP25"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_THEDA3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP25 lookup "HUSTR_25"\n'
    '{\n'
    '	titlepatch = "CWILV24"\n'
    '	next = "MAP26"\n'
    '	secretnext = "MAP26"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ADRIAN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP26 lookup "HUSTR_26"\n'
    '{\n'
    '	titlepatch = "CWILV25"\n'
    '	next = "MAP27"\n'
    '	secretnext = "MAP27"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_MESSG2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP27 lookup "HUSTR_27"\n'
    '{\n'
    '	titlepatch = "CWILV26"\n'
    '	next = "MAP28"\n'
    '	secretnext = "MAP28"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ROMER2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP28 lookup "HUSTR_28"\n'
    '{\n'
    '	titlepatch = "CWILV27"\n'
    '	next = "MAP29"\n'
    '	secretnext = "MAP29"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_TENSE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP29 lookup "HUSTR_29"\n'
    '{\n'
    '	titlepatch = "CWILV28"\n'
    '	next = "MAP30"\n'
    '	secretnext = "MAP30"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_SHAWN3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP30 lookup "HUSTR_30"\n'
    '{\n'
    '	titlepatch = "CWILV29"\n'
    '	next = "EndTitle"\n'
    '	secretnext = "EndTitle"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 7\n'
    '	par = 300\n'
    '	music = "$MUSIC_OPENIN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP31 lookup "HUSTR_31"\n'
    '{\n'
    '	titlepatch = "CWILV30"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP32"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 8\n'
    '	par = 300\n'
    '	music = "$MUSIC_EVIL"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP32 lookup "HUSTR_32"\n'
    '{\n'
    '	titlepatch = "CWILV31"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP16"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 9\n'
    '	par = 300\n'
    '	music = "$MUSIC_ULTIMA"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    '// DOOM II - First Half. Midway Mark & Secret Bonus Reminder.\n'
    '\n'
    'cluster 5\n'
    '{\n'
    '	flat = "$FLOOR0_3"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	exittext = \n'
    '	"HALFWAY THERE.", \n'
    '	" ",\n'
    '	"BONUS 1 ENTRANCE NEARBY."\n'
    '\n'
    '}\n'
    '\n'
    '// DOOM II - Second Half. Final Boss Warning.\n'
    '\n'
    'cluster 6\n'
    '{\n'
    '	flat = "$FLOOR0_3"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	exittext = \n'
    '	"WARNING!", \n'
    '	"FINAL BOSS AHEAD.", \n'
    '	" ",\n'
    '	"THIS IS IT.", \n'
    '	" ",\n'
    '	"FINISH THE FIGHT!"\n'
    '}\n'
    '\n'
    '// DOOM II - VICTORY\n'
    '\n'
    'cluster 7\n'
    '{\n'
    '	flat = "$BGFLAT06"\n'
    '	music = "$MUSIC_DM2TTL"\n'
    '	exittext = \n'
    '	"MISSION ACCOMPLISHED!!!",\n'
    '	"THE ENEMY HAS BEEN DEFEATED.",\n'
    '	"THE WORLD IS SAFE ONCE AGAIN.",\n'
    '	"THANK YOU HERO!",\n'
    '	" ",\n'
    '	"SEE YOU NEXT MISSION!"\n'
    '}\n'
    '\n'
    '// DOOM II - MAP31 Bonus 1\n'
    '\n'
    'cluster 8\n'
    '{\n'
    '	flat = "$FLOOR0_1"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	entertext = \n'
    '	"WELCOME TO BONUS 1!"\n'
    '}\n'
    '\n'
    '// DOOM II - MAP32 Bonus 2\n'
    '\n'
    'cluster 9\n'
    '{\n'
    '	flat = "$FLOOR0_1"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	entertext = \n'
    '	"WELCOME TO BONUS 2!"\n'
    '}\n'
}

UINT.mapinfofl4 =
{
    '// MAPINFO for Doom 2 - Intermission Wrapper Mod for OBLIGE generated 32-Map Megawads\n'
    '\n'
    'defaultmap\n'
    '{\n'
    '	sucktime = 5\n'
    '}\n'
    '\n'
    'map MAP01 lookup "HUSTR_1"\n'
    '{\n'
    '	titlepatch = "CWILV00"\n'
    '	next = "MAP02"\n'
    '	secretnext = "MAP02"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_RUNNIN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP02 lookup "HUSTR_2"\n'
    '{\n'
    '	titlepatch = "CWILV01"\n'
    '	next = "MAP03"\n'
    '	secretnext = "MAP03"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_STALKS"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP03 lookup "HUSTR_3"\n'
    '{\n'
    '	titlepatch = "CWILV02"\n'
    '	next = "MAP04"\n'
    '	secretnext = "MAP04"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_COUNTD"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP04 lookup "HUSTR_4"\n'
    '{\n'
    '	titlepatch = "CWILV03"\n'
    '	next = "EndTitle"\n'
    '	secretnext = "EndTitle"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 7\n'
    '	par = 300\n'
    '	music = "$MUSIC_BETWEE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP05 lookup "HUSTR_5"\n'
    '{\n'
    '	titlepatch = "CWILV04"\n'
    '	next = "MAP06"\n'
    '	secretnext = "MAP06"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DOOM"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP06 lookup "HUSTR_6"\n'
    '{\n'
    '	titlepatch = "CWILV05"\n'
    '	next = "MAP07"\n'
    '	secretnext = "MAP07"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_THE_DA"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP07 lookup "HUSTR_7"\n'
    '{\n'
    '	titlepatch = "CWILV06"\n'
    '	next = "MAP08"\n'
    '	secretnext = "MAP08"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	map07special\n'
    '	music = "$MUSIC_SHAWN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP08 lookup "HUSTR_8"\n'
    '{\n'
    '	titlepatch = "CWILV07"\n'
    '	next = "MAP09"\n'
    '	secretnext = "MAP09"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBLU"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP09 lookup "HUSTR_9"\n'
    '{\n'
    '	titlepatch = "CWILV08"\n'
    '	next = "MAP10"\n'
    '	secretnext = "MAP10"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_IN_CIT"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP10 lookup "HUSTR_10"\n'
    '{\n'
    '	titlepatch = "CWILV09"\n'
    '	next = "MAP11"\n'
    '	secretnext = "MAP11"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DEAD"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP11 lookup "HUSTR_11"\n'
    '{\n'
    '	titlepatch = "CWILV10"\n'
    '	next = "MAP12"\n'
    '	secretnext = "MAP12"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_STLKS2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP12 lookup "HUSTR_12"\n'
    '{\n'
    '	titlepatch = "CWILV11"\n'
    '	next = "MAP13"\n'
    '	secretnext = "MAP13"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_THEDA2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP13 lookup "HUSTR_13"\n'
    '{\n'
    '	titlepatch = "CWILV12"\n'
    '	next = "MAP14"\n'
    '	secretnext = "MAP14"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DOOM2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP14 lookup "HUSTR_14"\n'
    '{\n'
    '	titlepatch = "CWILV13"\n'
    '	next = "MAP15"\n'
    '	secretnext = "MAP15"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBL2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP15 lookup "HUSTR_15"\n'
    '{\n'
    '	titlepatch = "CWILV14"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP31"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_RUNNI2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP16 lookup "HUSTR_16"\n'
    '{\n'
    '	titlepatch = "CWILV15"\n'
    '	next = "MAP17"\n'
    '	secretnext = "MAP17"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_DEAD2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP17 lookup "HUSTR_17"\n'
    '{\n'
    '	titlepatch = "CWILV16"\n'
    '	next = "MAP18"\n'
    '	secretnext = "MAP18"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_STLKS3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP18 lookup "HUSTR_18"\n'
    '{\n'
    '	titlepatch = "CWILV17"\n'
    '	next = "MAP19"\n'
    '	secretnext = "MAP19"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ROMERO"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP19 lookup "HUSTR_19"\n'
    '{\n'
    '	titlepatch = "CWILV18"\n'
    '	next = "MAP20"\n'
    '	secretnext = "MAP20"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_SHAWN2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP20 lookup "HUSTR_20"\n'
    '{\n'
    '	titlepatch = "CWILV19"\n'
    '	next = "MAP21"\n'
    '	secretnext = "MAP21"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_MESSAG"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP21 lookup "HUSTR_21"\n'
    '{\n'
    '	titlepatch = "CWILV20"\n'
    '	next = "MAP22"\n'
    '	secretnext = "MAP22"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_COUNT2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP22 lookup "HUSTR_22"\n'
    '{\n'
    '	titlepatch = "CWILV21"\n'
    '	next = "MAP23"\n'
    '	secretnext = "MAP23"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBL3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP23 lookup "HUSTR_23"\n'
    '{\n'
    '	titlepatch = "CWILV22"\n'
    '	next = "MAP24"\n'
    '	secretnext = "MAP24"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_AMPIE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP24 lookup "HUSTR_24"\n'
    '{\n'
    '	titlepatch = "CWILV23"\n'
    '	next = "MAP25"\n'
    '	secretnext = "MAP25"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_THEDA3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP25 lookup "HUSTR_25"\n'
    '{\n'
    '	titlepatch = "CWILV24"\n'
    '	next = "MAP26"\n'
    '	secretnext = "MAP26"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ADRIAN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP26 lookup "HUSTR_26"\n'
    '{\n'
    '	titlepatch = "CWILV25"\n'
    '	next = "MAP27"\n'
    '	secretnext = "MAP27"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_MESSG2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP27 lookup "HUSTR_27"\n'
    '{\n'
    '	titlepatch = "CWILV26"\n'
    '	next = "MAP28"\n'
    '	secretnext = "MAP28"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ROMER2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP28 lookup "HUSTR_28"\n'
    '{\n'
    '	titlepatch = "CWILV27"\n'
    '	next = "MAP29"\n'
    '	secretnext = "MAP29"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_TENSE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP29 lookup "HUSTR_29"\n'
    '{\n'
    '	titlepatch = "CWILV28"\n'
    '	next = "MAP30"\n'
    '	secretnext = "MAP30"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_SHAWN3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP30 lookup "HUSTR_30"\n'
    '{\n'
    '	titlepatch = "CWILV29"\n'
    '	next = "EndTitle"\n'
    '	secretnext = "EndTitle"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 7\n'
    '	par = 300\n'
    '	music = "$MUSIC_OPENIN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP31 lookup "HUSTR_31"\n'
    '{\n'
    '	titlepatch = "CWILV30"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP32"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 8\n'
    '	par = 300\n'
    '	music = "$MUSIC_EVIL"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP32 lookup "HUSTR_32"\n'
    '{\n'
    '	titlepatch = "CWILV31"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP16"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 9\n'
    '	par = 300\n'
    '	music = "$MUSIC_ULTIMA"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    '// DOOM II - First Half. Midway Mark & Secret Bonus Reminder.\n'
    '\n'
    'cluster 5\n'
    '{\n'
    '	flat = "$FLOOR0_3"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	exittext = \n'
    '	"LAST LEVEL.", \n'
    '	" ",\n'
    '	"GIVE IT YOUR BEST!"\n'
    '\n'
    '}\n'
    '\n'
    '// DOOM II - Second Half. Final Boss Warning.\n'
    '\n'
    'cluster 6\n'
    '{\n'
    '	flat = "$FLOOR0_3"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	exittext = \n'
    '	"WARNING!", \n'
    '	"FINAL BOSS AHEAD.", \n'
    '	" ",\n'
    '	"THIS IS IT.", \n'
    '	" ",\n'
    '	"FINISH THE FIGHT!"\n'
    '}\n'
    '\n'
    '// DOOM II - VICTORY\n'
    '\n'
    'cluster 7\n'
    '{\n'
    '	flat = "$BGFLAT06"\n'
    '	music = "$MUSIC_DM2TTL"\n'
    '	exittext = \n'
    '	"MISSION ACCOMPLISHED!!!",\n'
    '	"THE ENEMY HAS BEEN DEFEATED.",\n'
    '	"THE WORLD IS SAFE ONCE AGAIN.",\n'
    '	"THANK YOU HERO!",\n'
    '	" ",\n'
    '	"SEE YOU NEXT MISSION!"\n'
    '}\n'
    '\n'
    '// DOOM II - MAP31 Bonus 1\n'
    '\n'
    'cluster 8\n'
    '{\n'
    '	flat = "$FLOOR0_1"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	entertext = \n'
    '	"WELCOME TO BONUS 1!"\n'
    '}\n'
    '\n'
    '// DOOM II - MAP32 Bonus 2\n'
    '\n'
    'cluster 9\n'
    '{\n'
    '	flat = "$FLOOR0_1"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	entertext = \n'
    '	"WELCOME TO BONUS 2!"\n'
    '}\n'
}

UINT.mapinfoep11 =
{
    '// MAPINFO for Doom 2 - Intermission Wrapper Mod for OBLIGE generated 32-Map Megawads\n'
    '\n'
    'defaultmap\n'
    '{\n'
    '	sucktime = 5\n'
    '}\n'
    '\n'
    'map MAP01 lookup "HUSTR_1"\n'
    '{\n'
    '	titlepatch = "CWILV00"\n'
    '	next = "MAP02"\n'
    '	secretnext = "MAP02"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_RUNNIN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP02 lookup "HUSTR_2"\n'
    '{\n'
    '	titlepatch = "CWILV01"\n'
    '	next = "MAP03"\n'
    '	secretnext = "MAP03"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_STALKS"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP03 lookup "HUSTR_3"\n'
    '{\n'
    '	titlepatch = "CWILV02"\n'
    '	next = "MAP04"\n'
    '	secretnext = "MAP04"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_COUNTD"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP04 lookup "HUSTR_4"\n'
    '{\n'
    '	titlepatch = "CWILV03"\n'
    '	next = "MAP05"\n'
    '	secretnext = "MAP05"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_BETWEE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP05 lookup "HUSTR_5"\n'
    '{\n'
    '	titlepatch = "CWILV04"\n'
    '	next = "MAP06"\n'
    '	secretnext = "MAP06"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DOOM"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP06 lookup "HUSTR_6"\n'
    '{\n'
    '	titlepatch = "CWILV05"\n'
    '	next = "MAP07"\n'
    '	secretnext = "MAP07"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_THE_DA"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP07 lookup "HUSTR_7"\n'
    '{\n'
    '	titlepatch = "CWILV06"\n'
    '	next = "MAP08"\n'
    '	secretnext = "MAP08"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	map07special\n'
    '	music = "$MUSIC_SHAWN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP08 lookup "HUSTR_8"\n'
    '{\n'
    '	titlepatch = "CWILV07"\n'
    '	next = "MAP09"\n'
    '	secretnext = "MAP09"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBLU"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP09 lookup "HUSTR_9"\n'
    '{\n'
    '	titlepatch = "CWILV08"\n'
    '	next = "MAP10"\n'
    '	secretnext = "MAP10"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_IN_CIT"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP10 lookup "HUSTR_10"\n'
    '{\n'
    '	titlepatch = "CWILV09"\n'
    '	next = "MAP11"\n'
    '	secretnext = "MAP11"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DEAD"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP11 lookup "HUSTR_11"\n'
    '{\n'
    '	titlepatch = "CWILV10"\n'
    '	next = "EndTitle"\n'
    '	secretnext = "EndTitle"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 7\n'
    '	par = 300\n'
    '	music = "$MUSIC_STLKS2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP12 lookup "HUSTR_12"\n'
    '{\n'
    '	titlepatch = "CWILV11"\n'
    '	next = "MAP13"\n'
    '	secretnext = "MAP13"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_THEDA2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP13 lookup "HUSTR_13"\n'
    '{\n'
    '	titlepatch = "CWILV12"\n'
    '	next = "MAP14"\n'
    '	secretnext = "MAP14"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DOOM2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP14 lookup "HUSTR_14"\n'
    '{\n'
    '	titlepatch = "CWILV13"\n'
    '	next = "MAP15"\n'
    '	secretnext = "MAP15"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBL2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP15 lookup "HUSTR_15"\n'
    '{\n'
    '	titlepatch = "CWILV14"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP31"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_RUNNI2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP16 lookup "HUSTR_16"\n'
    '{\n'
    '	titlepatch = "CWILV15"\n'
    '	next = "MAP17"\n'
    '	secretnext = "MAP17"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_DEAD2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP17 lookup "HUSTR_17"\n'
    '{\n'
    '	titlepatch = "CWILV16"\n'
    '	next = "MAP18"\n'
    '	secretnext = "MAP18"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_STLKS3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP18 lookup "HUSTR_18"\n'
    '{\n'
    '	titlepatch = "CWILV17"\n'
    '	next = "MAP19"\n'
    '	secretnext = "MAP19"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ROMERO"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP19 lookup "HUSTR_19"\n'
    '{\n'
    '	titlepatch = "CWILV18"\n'
    '	next = "MAP20"\n'
    '	secretnext = "MAP20"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_SHAWN2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP20 lookup "HUSTR_20"\n'
    '{\n'
    '	titlepatch = "CWILV19"\n'
    '	next = "MAP21"\n'
    '	secretnext = "MAP21"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_MESSAG"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP21 lookup "HUSTR_21"\n'
    '{\n'
    '	titlepatch = "CWILV20"\n'
    '	next = "MAP22"\n'
    '	secretnext = "MAP22"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_COUNT2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP22 lookup "HUSTR_22"\n'
    '{\n'
    '	titlepatch = "CWILV21"\n'
    '	next = "MAP23"\n'
    '	secretnext = "MAP23"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBL3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP23 lookup "HUSTR_23"\n'
    '{\n'
    '	titlepatch = "CWILV22"\n'
    '	next = "MAP24"\n'
    '	secretnext = "MAP24"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_AMPIE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP24 lookup "HUSTR_24"\n'
    '{\n'
    '	titlepatch = "CWILV23"\n'
    '	next = "MAP25"\n'
    '	secretnext = "MAP25"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_THEDA3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP25 lookup "HUSTR_25"\n'
    '{\n'
    '	titlepatch = "CWILV24"\n'
    '	next = "MAP26"\n'
    '	secretnext = "MAP26"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ADRIAN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP26 lookup "HUSTR_26"\n'
    '{\n'
    '	titlepatch = "CWILV25"\n'
    '	next = "MAP27"\n'
    '	secretnext = "MAP27"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_MESSG2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP27 lookup "HUSTR_27"\n'
    '{\n'
    '	titlepatch = "CWILV26"\n'
    '	next = "MAP28"\n'
    '	secretnext = "MAP28"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ROMER2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP28 lookup "HUSTR_28"\n'
    '{\n'
    '	titlepatch = "CWILV27"\n'
    '	next = "MAP29"\n'
    '	secretnext = "MAP29"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_TENSE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP29 lookup "HUSTR_29"\n'
    '{\n'
    '	titlepatch = "CWILV28"\n'
    '	next = "MAP30"\n'
    '	secretnext = "MAP30"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_SHAWN3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP30 lookup "HUSTR_30"\n'
    '{\n'
    '	titlepatch = "CWILV29"\n'
    '	next = "EndTitle"\n'
    '	secretnext = "EndTitle"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 7\n'
    '	par = 300\n'
    '	music = "$MUSIC_OPENIN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP31 lookup "HUSTR_31"\n'
    '{\n'
    '	titlepatch = "CWILV30"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP32"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 8\n'
    '	par = 300\n'
    '	music = "$MUSIC_EVIL"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP32 lookup "HUSTR_32"\n'
    '{\n'
    '	titlepatch = "CWILV31"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP16"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 9\n'
    '	par = 300\n'
    '	music = "$MUSIC_ULTIMA"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    '// DOOM II - First Half. Midway Mark & Secret Bonus Reminder.\n'
    '\n'
    'cluster 5\n'
    '{\n'
    '	flat = "$FLOOR0_3"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	exittext = \n'
    '	"LAST LEVEL.", \n'
    '	" ",\n'
    '	"GIVE IT YOUR BEST!"\n'
    '\n'
    '}\n'
    '\n'
    '// DOOM II - Second Half. Final Boss Warning.\n'
    '\n'
    'cluster 6\n'
    '{\n'
    '	flat = "$FLOOR0_3"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	exittext = \n'
    '	"WARNING!", \n'
    '	"FINAL BOSS AHEAD.", \n'
    '	" ",\n'
    '	"THIS IS IT.", \n'
    '	" ",\n'
    '	"FINISH THE FIGHT!"\n'
    '}\n'
    '\n'
    '// DOOM II - VICTORY\n'
    '\n'
    'cluster 7\n'
    '{\n'
    '	flat = "$BGFLAT06"\n'
    '	music = "$MUSIC_DM2TTL"\n'
    '	exittext = \n'
    '	"MISSION ACCOMPLISHED!!!",\n'
    '	"THE ENEMY HAS BEEN DEFEATED.",\n'
    '	"THE WORLD IS SAFE ONCE AGAIN.",\n'
    '	"THANK YOU HERO!",\n'
    '	" ",\n'
    '	"SEE YOU NEXT MISSION!"\n'
    '}\n'
    '\n'
    '// DOOM II - MAP31 Bonus 1\n'
    '\n'
    'cluster 8\n'
    '{\n'
    '	flat = "$FLOOR0_1"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	entertext = \n'
    '	"WELCOME TO BONUS 1!"\n'
    '}\n'
    '\n'
    '// DOOM II - MAP32 Bonus 2\n'
    '\n'
    'cluster 9\n'
    '{\n'
    '	flat = "$FLOOR0_1"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	entertext = \n'
    '	"WELCOME TO BONUS 2!"\n'
    '}\n'
}

UINT.mapinfomw32 =
{
    '// MAPINFO for Doom 2 - Intermission Wrapper Mod for OBLIGE generated 32-Map Megawads\n'
    '\n'
    'defaultmap\n'
    '{\n'
    '	sucktime = 5\n'
    '}\n'
    '\n'
    'map MAP01 lookup "HUSTR_1"\n'
    '{\n'
    '	titlepatch = "CWILV00"\n'
    '	next = "MAP02"\n'
    '	secretnext = "MAP02"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_RUNNIN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP02 lookup "HUSTR_2"\n'
    '{\n'
    '	titlepatch = "CWILV01"\n'
    '	next = "MAP03"\n'
    '	secretnext = "MAP03"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_STALKS"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP03 lookup "HUSTR_3"\n'
    '{\n'
    '	titlepatch = "CWILV02"\n'
    '	next = "MAP04"\n'
    '	secretnext = "MAP04"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_COUNTD"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP04 lookup "HUSTR_4"\n'
    '{\n'
    '	titlepatch = "CWILV03"\n'
    '	next = "MAP05"\n'
    '	secretnext = "MAP05"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_BETWEE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP05 lookup "HUSTR_5"\n'
    '{\n'
    '	titlepatch = "CWILV04"\n'
    '	next = "MAP06"\n'
    '	secretnext = "MAP06"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DOOM"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP06 lookup "HUSTR_6"\n'
    '{\n'
    '	titlepatch = "CWILV05"\n'
    '	next = "MAP07"\n'
    '	secretnext = "MAP07"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_THE_DA"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP07 lookup "HUSTR_7"\n'
    '{\n'
    '	titlepatch = "CWILV06"\n'
    '	next = "MAP08"\n'
    '	secretnext = "MAP08"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	map07special\n'
    '	music = "$MUSIC_SHAWN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP08 lookup "HUSTR_8"\n'
    '{\n'
    '	titlepatch = "CWILV07"\n'
    '	next = "MAP09"\n'
    '	secretnext = "MAP09"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBLU"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP09 lookup "HUSTR_9"\n'
    '{\n'
    '	titlepatch = "CWILV08"\n'
    '	next = "MAP10"\n'
    '	secretnext = "MAP10"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_IN_CIT"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP10 lookup "HUSTR_10"\n'
    '{\n'
    '	titlepatch = "CWILV09"\n'
    '	next = "MAP11"\n'
    '	secretnext = "MAP11"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DEAD"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP11 lookup "HUSTR_11"\n'
    '{\n'
    '	titlepatch = "CWILV10"\n'
    '	next = "MAP12"\n'
    '	secretnext = "MAP12"\n'
    '	sky1 = "SKY1"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_STLKS2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP12 lookup "HUSTR_12"\n'
    '{\n'
    '	titlepatch = "CWILV11"\n'
    '	next = "MAP13"\n'
    '	secretnext = "MAP13"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_THEDA2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP13 lookup "HUSTR_13"\n'
    '{\n'
    '	titlepatch = "CWILV12"\n'
    '	next = "MAP14"\n'
    '	secretnext = "MAP14"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DOOM2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP14 lookup "HUSTR_14"\n'
    '{\n'
    '	titlepatch = "CWILV13"\n'
    '	next = "MAP15"\n'
    '	secretnext = "MAP15"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 5\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBL2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP15 lookup "HUSTR_15"\n'
    '{\n'
    '	titlepatch = "CWILV14"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP31"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_RUNNI2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP16 lookup "HUSTR_16"\n'
    '{\n'
    '	titlepatch = "CWILV15"\n'
    '	next = "MAP17"\n'
    '	secretnext = "MAP17"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_DEAD2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP17 lookup "HUSTR_17"\n'
    '{\n'
    '	titlepatch = "CWILV16"\n'
    '	next = "MAP18"\n'
    '	secretnext = "MAP18"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_STLKS3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP18 lookup "HUSTR_18"\n'
    '{\n'
    '	titlepatch = "CWILV17"\n'
    '	next = "MAP19"\n'
    '	secretnext = "MAP19"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ROMERO"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP19 lookup "HUSTR_19"\n'
    '{\n'
    '	titlepatch = "CWILV18"\n'
    '	next = "MAP20"\n'
    '	secretnext = "MAP20"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_SHAWN2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP20 lookup "HUSTR_20"\n'
    '{\n'
    '	titlepatch = "CWILV19"\n'
    '	next = "MAP21"\n'
    '	secretnext = "MAP21"\n'
    '	sky1 = "SKY2"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_MESSAG"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP21 lookup "HUSTR_21"\n'
    '{\n'
    '	titlepatch = "CWILV20"\n'
    '	next = "MAP22"\n'
    '	secretnext = "MAP22"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_COUNT2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP22 lookup "HUSTR_22"\n'
    '{\n'
    '	titlepatch = "CWILV21"\n'
    '	next = "MAP23"\n'
    '	secretnext = "MAP23"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_DDTBL3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP23 lookup "HUSTR_23"\n'
    '{\n'
    '	titlepatch = "CWILV22"\n'
    '	next = "MAP24"\n'
    '	secretnext = "MAP24"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_AMPIE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP24 lookup "HUSTR_24"\n'
    '{\n'
    '	titlepatch = "CWILV23"\n'
    '	next = "MAP25"\n'
    '	secretnext = "MAP25"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_THEDA3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP25 lookup "HUSTR_25"\n'
    '{\n'
    '	titlepatch = "CWILV24"\n'
    '	next = "MAP26"\n'
    '	secretnext = "MAP26"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ADRIAN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP26 lookup "HUSTR_26"\n'
    '{\n'
    '	titlepatch = "CWILV25"\n'
    '	next = "MAP27"\n'
    '	secretnext = "MAP27"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_MESSG2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP27 lookup "HUSTR_27"\n'
    '{\n'
    '	titlepatch = "CWILV26"\n'
    '	next = "MAP28"\n'
    '	secretnext = "MAP28"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_ROMER2"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP28 lookup "HUSTR_28"\n'
    '{\n'
    '	titlepatch = "CWILV27"\n'
    '	next = "MAP29"\n'
    '	secretnext = "MAP29"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_TENSE"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP29 lookup "HUSTR_29"\n'
    '{\n'
    '	titlepatch = "CWILV28"\n'
    '	next = "MAP30"\n'
    '	secretnext = "MAP30"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 6\n'
    '	par = 300\n'
    '	music = "$MUSIC_SHAWN3"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP30 lookup "HUSTR_30"\n'
    '{\n'
    '	titlepatch = "CWILV29"\n'
    '	next = "EndTitle"\n'
    '	secretnext = "EndTitle"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 7\n'
    '	par = 300\n'
    '	music = "$MUSIC_OPENIN"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP31 lookup "HUSTR_31"\n'
    '{\n'
    '	titlepatch = "CWILV30"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP32"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 8\n'
    '	par = 300\n'
    '	music = "$MUSIC_EVIL"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    'map MAP32 lookup "HUSTR_32"\n'
    '{\n'
    '	titlepatch = "CWILV31"\n'
    '	next = "MAP16"\n'
    '	secretnext = "MAP16"\n'
    '	sky1 = "SKY3"\n'
    '	cluster = 9\n'
    '	par = 300\n'
    '	music = "$MUSIC_ULTIMA"\n'
    '	exitpic = "$INTM"\n'
    '	enterpic = "$INTM"\n'
    '}\n'
    '\n'
    '// DOOM II - First Half. Midway Mark & Secret Bonus Reminder.\n'
    '\n'
    'cluster 5\n'
    '{\n'
    '	flat = "$FLOOR0_3"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	exittext = \n'
    '	"HALFWAY THERE.", \n'
    '	" ",\n'
    '	"BONUS 1 ENTRANCE NEARBY."\n'
    '\n'
    '}\n'
    '\n'
    '// DOOM II - Second Half. Final Boss Warning.\n'
    '\n'
    'cluster 6\n'
    '{\n'
    '	flat = "$FLOOR0_3"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	exittext = \n'
    '	"WARNING!", \n'
    '	"FINAL BOSS AHEAD.", \n'
    '	" ",\n'
    '	"THIS IS IT.", \n'
    '	" ",\n'
    '	"FINISH THE FIGHT!"\n'
    '}\n'
    '\n'
    '// DOOM II - VICTORY\n'
    '\n'
    'cluster 7\n'
    '{\n'
    '	flat = "$BGFLAT06"\n'
    '	music = "$MUSIC_DM2TTL"\n'
    '	exittext = \n'
    '	"MISSION ACCOMPLISHED!!!",\n'
    '	"THE ENEMY HAS BEEN DEFEATED.",\n'
    '	"THE WORLD IS SAFE ONCE AGAIN.",\n'
    '	"THANK YOU HERO!",\n'
    '	" ",\n'
    '	"SEE YOU NEXT MISSION!"\n'
    '}\n'
    '\n'
    '// DOOM II - MAP31 Bonus 1\n'
    '\n'
    'cluster 8\n'
    '{\n'
    '	flat = "$FLOOR0_1"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	entertext = \n'
    '	"WELCOME TO BONUS 1!"\n'
    '}\n'
    '\n'
    '// DOOM II - MAP32 Bonus 2\n'
    '\n'
    'cluster 9\n'
    '{\n'
    '	flat = "$FLOOR0_1"\n'
    '	music = "$MUSIC_READ_M"\n'
    '	entertext = \n'
    '	"WELCOME TO BONUS 2!"\n'
    '}\n'
}